//
//  ComposingUnitCollectionViewCell.swift
//  Compose
//
//  Created by Bruno Bilescky on 05/10/16.
//  Copyright © 2016 VivaReal. All rights reserved.
//

import UIKit

/// Generic cell that encapsulates another view inside it. You can use it to fast embed other views inside a UICollectionViewCell.
public class ComposingUnitCollectionViewCell<V: UIView>: UICollectionViewCell {
    
    private var currentConstraints: [NSLayoutConstraint] = []
    
    /// Embeded view (this view is generated by the CollectionViewCell)
    public private(set) var innerView: V!
    
    /// insets applied to the embeded view.
    public var insets: UIEdgeInsets = .zero
    
    override public init(frame: CGRect) {
        super.init(frame: frame)
        commonInit(frame: frame)
    }
    
    required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) not supported.")
    }
    
    private func commonInit(frame: CGRect) {
        self.isOpaque = false
        self.backgroundColor = .clear
        self.innerView = V(frame: frame)
        self.contentView.addSubview(innerView)
        self.innerView.translatesAutoresizingMaskIntoConstraints = false
    }
    
    /// You can apply some ViewTraits to the collectionViewCell, in order to configure it
    ///
    /// - parameter traits: an array of ViewTraits
    public func apply(traits: [ViewTraits]) {
        self.backgroundColor = .clear
        let result = ViewTraits.mapStyle(from: traits)
        self.insets = result.insets
        self.contentView.isOpaque = result.opaque
        self.contentView.backgroundColor = result.backgroundColor
    }
    
    /// update the insets of the inner view when moving to superview
    override public func didMoveToSuperview() {
        super.didMoveToSuperview()
        update(insets: insets)
    }
    
    /// Needed in order to update with animation the state of the cell
    ///
    /// - parameter layoutAttributes: layout attributes defined by the collectionView layout
    override public func apply(_ layoutAttributes: UICollectionViewLayoutAttributes) {
        UIView.animate(withDuration: 0.33) {
            self.update(insets: self.insets)
            self.layoutIfNeeded()
        }
    }
    
    private func update(insets: UIEdgeInsets, animated: Bool = false) {
        let superview = self
        superview.removeConstraints(currentConstraints)
        self.innerView.removeConstraints(currentConstraints)
        let leadingConstraint = NSLayoutConstraint(item: self.innerView, attribute: .leading, relatedBy: .equal, toItem: superview, attribute: .leading, multiplier: 1, constant: insets.left)
        let topConstraint = NSLayoutConstraint(item: self.innerView, attribute: .top, relatedBy: .equal, toItem: superview, attribute: .top, multiplier: 1, constant: insets.top)
        let trailingConstraint = NSLayoutConstraint(item: self.innerView, attribute: .trailing, relatedBy: .equal, toItem: superview, attribute: .trailing, multiplier: 1, constant: -insets.right)
        let bottomConstraint = NSLayoutConstraint(item: self.innerView, attribute: .bottom, relatedBy: .equal, toItem: superview, attribute: .bottom, multiplier: 1, constant: -insets.bottom)
        currentConstraints = [leadingConstraint, topConstraint, trailingConstraint, bottomConstraint]
        superview.addConstraints(currentConstraints)
    }
    
}
